#!/usr/bin/expect

set HOST localhost
set PORT 4303
set BUS 1

spawn telnet $HOST $PORT
expect "srcpd"
send "SET CONNECTIONMODE SRCP COMMAND\n"
expect "202 OK CONNECTIONMODE"
send "GO\n"
expect "200 OK GO"
send "INIT $BUS POWER\n"
expect "200 OK"
send "GET $BUS POWER\n"
expect "INFO $BUS POWER"
send "SET $BUS POWER ON\n"
expect "200 OK"
send "TERM $BUS SM\n"
expect "200 OK"
send "TERM 0 SESSION\n"
exit
