'\" t
.TH srcpd 8 
.SH NAME
srcpd \- SRCP speaking daemon
.SH SYNOPSIS
.B srcpd
[ options ] 
.SH DESCRIPTION
This is not a complete manual. You have to consult the project
home page at http://srcpd.sourceforge.net for full documentation!

.B srcpd
is a UNIX daemon speaking the simple railroad command protocol
SRCP.

Upon start up it reads in a configuration file named srcpd.conf
from the usual places. The SRCP itself is specified on 
http://srcpd.sourceforge.net/srcp.
.SH OPTIONS
.TP
.BI \-h
prints some useful help about command line options and exit
.TP
.BI \-v
print program version, SRCP Level and exit
.TP
.BI \-f <filename>
use the specified filename as the configuration file. The default
value will be defined at compile time and can be displayed using the
-h parameter.

.SH "SEE ALSO"
.BR http://srcpd.sourceforge.net/srcpd
.br
.I

.SH BUGS
There ARE bugs, we're sure.

.SH AUTHORS
the srcpd team on sourceforge

.SH LICENSE
General Public License, Version2
