#!/usr/bin/expect

set HOST localhost
set PORT 4303
set BUS 1
set ADDR 10

spawn telnet $HOST $PORT
expect "srcpd"
send "SET CONNECTIONMODE SRCP COMMAND\n"
expect "202 OK CONNECTIONMODE"
send "GO\n"
expect "200 OK GO"
send "INIT $BUS GL $ADDR N 2 128 28\n"
expect "200 OK"
send "GET $BUS GL $ADDR\n"
expect "100 INFO"
send "SET $BUS GL $ADDR 0 0 128 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1\n"
expect "200 OK"
send "GET $BUS GL $ADDR\n"
expect "100 INFO"
send "TERM $BUS GL $ADDR\n"
expect "200 OK"
send "TERM 0 SESSION\n"
exit
