'\" t
.TH srcpd 8 
.SH NAME
srcpd \- SRCP speaking daemon
.SH SYNOPSIS
.B srcpd
[ options ] 
.SH DESCRIPTION
This is not a complete manual. You have to consult the projects
home page for full documentation!

.B srcpd
is a unix daemon speaking the simple railroad command protocol
SRCP.

Upon startup it reads  a configuration file named srcpd.xml 
from the usual places. The SRCP is specified on 
http://www.der-moba.de/Digital.
.SH OPTIONS
.TP
.BI \-h
prints some useful text about command line options and exits
.TP
.BI \-v
prints program version, SRCP Level and exits

.SH "SEE ALSO"
.BR http://srcpd.sourceforge.net/srcpd
.br
.I

.SH BUGS
There ARE bugs, we're sure.

.SH AUTHROS
The srcpd team on sourceforge

.SH LICENSE
General Public License Version2 1991
