#!/bin/sh
#
# simples Script. Testet nur, ob wir auf FreeBSD sind, da dort die
# Linkeroption fuer die Threads anders ist.
# Wird im Makefile mit aufgerufen
#
# 01/06/03 MAM
#

a=`uname -s`
if [ "$a" = "FreeBSD" ]
then
	echo "-pthread"
else
	echo "-lpthread"
fi

